
RTMON_DIR_PATH := ../../third-party/rt-monitor

COMPONENT_ADD_INCLUDEDIRS := ${RTMON_DIR_PATH}

COMPONENT_PRIV_INCLUDEDIRS := ../config
COMPONENT_PRIV_INCLUDEDIRS += ${RTMON_DIR_PATH}/port/inc
 
COMPONENT_SRCDIRS := ${RTMON_DIR_PATH}
COMPONENT_SRCDIRS += ${RTMON_DIR_PATH}/port/ESP8266

CPPFLAGS += -Wno-format
#${SMON_DIR_PATH}/src/smonitor.o: CFLAGS += -Wno-format
